# Generated by Django 6.0.4 on 2026-04-16 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.TextField(unique=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='registered', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MFT_SI', '$MFT STANDARD_INFORMATION'), ('MFT_FN', '$MFT FILE_NAME'), ('USN', '$UsnJrnl'), ('LOGFILE', '$LogFile'), ('REGISTRY', 'Windows Registry'), ('EVTX', 'Event Log (EVTX)'), ('VSS', 'Volume Shadow Copy')], max_length=20)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=512)),
                ('inode', models.BigIntegerField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
                ('changed_time', models.DateTimeField(blank=True, null=True)),
                ('born_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_directory', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.diskimage')),
            ],
            options={
                'ordering': ['file_path', 'source'],
            },
        ),
        migrations.CreateModel(
            name='ForgeryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=512)),
                ('forgery_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('genuine', 'Genuine'), ('suspicious', 'Suspicious'), ('forged', 'Forged')], default='genuine', max_length=20)),
                ('anomalies', models.JSONField(default=list)),
                ('scoring_breakdown', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgery_results', to='core.diskimage')),
            ],
            options={
                'ordering': ['-forgery_score'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('created', 'File Created'), ('modified', 'File Modified'), ('accessed', 'File Accessed'), ('changed', 'MFT Entry Changed'), ('deleted', 'File Deleted'), ('renamed', 'File Renamed'), ('usn_event', 'USN Journal Event'), ('log_event', 'LogFile Event'), ('registry_event', 'Registry Event'), ('evtx_event', 'Event Log Entry')], max_length=30)),
                ('source', models.CharField(max_length=20)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='core.forensicartifact')),
                ('disk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.diskimage')),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
    ]
