# Generated by Django 6.0.4 on 2026-04-29 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diskimage_hash_algorithm_alter_diskimage_sha256_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diskimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
