# Generated by Django 6.0.4 on 2026-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_investigator_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskimage',
            name='analysis_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diskimage',
            name='analysis_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diskimage',
            name='analysis_status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='diskimage',
            name='scoring_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diskimage',
            name='scoring_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diskimage',
            name='scoring_status',
            field=models.CharField(default='idle', max_length=20),
        ),
    ]
