# Generated by Django 6.0.4 on 2026-04-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('artifacts_extracted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('disk_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_job', to='core.diskimage')),
            ],
        ),
    ]
