# Generated by Django 6.0.4 on 2026-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='current_step_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='total_steps',
            field=models.IntegerField(default=5),
        ),
    ]
